### ISSUE TITLE
Are you planning on adding a reply feature?

### ISSUE THREAD

**Issue by denito** [philhawksworth/jamstack-comments-engine#2]
Hi there - This is a nice engine congrats.  I was wondering if you had any interest in adding a reply hierarchy (just one level)?  Thus indenting replies to individual comments?

**Comment by donaldboulton** [comment]
Here is the reply code if ya want to try it yourself. [`Code at my Repo`](https://github.com/donaldboulton/DWB/blob/gh-pages/build/js/staticman/staticman-comments-reply.js)
The code originally was from Staticman's APi .js to post the form as a pull request. The reply code was taken from Wordpress replies and rebuilt by Michael Rose on Minimal Mistakes: [MMistakes](https://github.com/mmistakes/minimal-mistakes)
I am working on Jamstact Comments in donboulton.com, a Jekyll React Webpack Site. I have got the form to post approved-comments to Netlify forms and the Functions sent the .json to Slack for approval. have not got it to do the pull request for github to post the data to my Jekyll _data comments.json,  and need to loop over the data file for display, but working on it.

**Comment by philhawksworth** [comment]
I'm not planning on adding that feature to this demo, @denito. 

This is more of a reference example than a product (hence the outrageous delay in replying.. sorry about that!) so I'm trying to just illustrate some core concepts while avoiding adding too many more other features which might make it harder for people to grasp the underlying model and flows.
