### ISSUE TITLE
"Deploy to Netlify" button not successful

### ISSUE THREAD

**Issue by yukster** [philhawksworth/jamstack-comments-engine#3]
Tried the "Deploy to Netlify" button today but the Netlify build fails with:

```error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.15.3"```

**Comment by philhawksworth** [comment]
Ah! Looks like some dependencies have moved along. I specify the use of node v8.9.0 in the netlify.toml file, which is what Netlify will honour. But you'd need to use that in your local build too.

The world has moved along a bit. Using something like nvm to manage which version of node you use locally will help. But I'm updating some dependencies now, so I'll bring this all up to date.

**Comment by philhawksworth** [comment]
Dependencies updated. The deploy to netlify button should now be operation again.
Thanks for reporting this @yukster, and apologies for such a long delay in taking a look.
